apiVersion: v1
kind: Service
metadata:
  name: service-1-deployment
  labels:
    run: service-1
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: service-1
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: service-1-deployment
spec:
  selector:
    matchLabels:
      app: service-1
  replicas: 1
  template:
    metadata:
      labels:
        app: service-1
    spec:
      containers:
      - name: service-1
        image: gcr.io/kubernetis-practise-1/server-example:v4
        ports:
        - containerPort: 80